nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://localhost:3000']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    
    paths:
        '^/api/':
            allow_origin: ['https://localhost:3000']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
        '^/': null
